# Generated by Django 4.1.7 on 2023-03-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'female')], default='Male', max_length=7),
        ),
    ]
